from sqlalchemy import Column, Integer, Float, DateTime, String, ForeignKey
from sqlalchemy.sql import func
from app.database import Base


class Order(Base):
    __tablename__ = "orders"

    id = Column(Integer, primary_key=True, index=True)
    order_number = Column(String(50), unique=True, index=True, nullable=True)
    customer_name = Column(String(100), nullable=True)

    pickup_address = Column(String(255), nullable=True)
    pickup_latitude = Column(Float, nullable=False)
    pickup_longitude = Column(Float, nullable=False)

    delivery_address = Column(String(255), nullable=True)
    delivery_latitude = Column(Float, nullable=False)
    delivery_longitude = Column(Float, nullable=False)

    weight = Column(Float, nullable=False)
    priority = Column(Integer, default=1)

    delivery_deadline = Column(DateTime, nullable=True)

    # Lifecycle status: pending, assigned, planned, pickup_pending, picked_up, out_for_delivery, delivered, cancelled
    status = Column(
        String(30),
        default="pending",
        nullable=False
    )

    # Delivery performance status: pending, on_time, at_risk, delayed, delivered
    delivery_status = Column(
        String(30),
        default="pending",
        nullable=False
    )

    assigned_driver_id = Column(
        Integer,
        ForeignKey("drivers.id", ondelete="SET NULL"),
        nullable=True
    )

    route_id = Column(
        Integer,
        ForeignKey("routes.id", ondelete="SET NULL"),
        nullable=True
    )

    # ETA generated by optimizer or router
    estimated_arrival = Column(
        DateTime,
        nullable=True
    )

    created_at = Column(
        DateTime,
        server_default=func.now(),
        nullable=True
    )

    updated_at = Column(
        DateTime,
        server_default=func.now(),
        onupdate=func.now(),
        nullable=True
    )